repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.18.0
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  #       types: [file]
  #       additional_dependencies:
  #         - eslint
  #         - eslint-config-google
  #         - eslint-loader
  #         - eslint-plugin-react
  #         - babel-eslint
